### ISSUE TITLE
[Bug] Last scanned not properly displayed when holding mouse pointer over gym

### ISSUE THREAD

**Issue by ghost** [sebastienvercammen/devkat-rm-node-webserver#2] opened 2017-11-26 20:45 UTC
Last scanned is actually "a minute ago" according to sidebar, but shows as 2 hours ago when holding mouse pointer over gym.

See image for better explanation. 
https://i.imgur.com/1ucNTUS.png

**Comment by crhbetz** [comment] 2017-11-27 12:01
It seems to be the "last modified" time showing as "last scanned". At least it's always the same for me when below 1 hour.

**Comment by sebastienvercammen** [comment] 2018-01-06 15:30
This was caused by two separate tables having the same field name and was fixed in a9ba9d7a7ffc35f93e59b7f9ce636ae27e842178.

**Closed as completed by sebastienvercammen** 2018-01-06 15:30 UTC
Labels: bug
